exclude: 'docs|node_modules|env|migrations|.git|.tox'
default_stages: [commit]
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-yaml

  # - repo: https://github.com/psf/black
  #   rev: 21.6b0
  #   hooks:
  #     - id: black

#  - repo: https://github.com/timothycrosley/isort
#    rev: 5.9.1
#    hooks:
#      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ['--config=setup.cfg', '--ignore=F405,E501']
#        additional_dependencies: [flake8-isort]


# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false
