version: '3.11'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/myheritage
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=mydatabaseuser
      - DB_PASSWORD=mypassword
      - JWT_SECRET_KEY=mysecretkey
